apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  labels:
    app: postgres
data:
  DB_HOST: project3-postgres-postgresql
  DB_PORT: 5432
  DB_NAME: postgres
  DB_USERNAME: postgres