apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  # POSTGRES_PASSWORD: password123
  POSTGRES_PASSWORD: BGjnWtmKXh